//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeneciaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int id { get; set; }
        public Nullable<int> emptime { get; set; }
        public string empstatus { get; set; }
        public Nullable<int> supervisorname { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string notes { get; set; }
        public Nullable<System.TimeSpan> times { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
