//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeneciaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class cage
    {
        public cage()
        {
            this.cagedetails = new HashSet<cagedetails>();
            this.qualityofwater = new HashSet<qualityofwater>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> feed { get; set; }
        public Nullable<double> sources { get; set; }
        public Nullable<double> gainedfish { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
        public Nullable<System.TimeSpan> times { get; set; }
    
        public virtual feed feed1 { get; set; }
        public virtual ICollection<cagedetails> cagedetails { get; set; }
        public virtual ICollection<qualityofwater> qualityofwater { get; set; }
    }
}
