//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeneciaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public Nullable<int> msgfrom { get; set; }
        public Nullable<int> msgto { get; set; }
        public string msgsubject { get; set; }
        public string messages1 { get; set; }
        public Nullable<System.DateTime> msgdate { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
