//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeneciaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class productdetails
    {
        public productdetails()
        {
            this.products = new HashSet<products>();
            this.products1 = new HashSet<products>();
            this.products2 = new HashSet<products>();
            this.products3 = new HashSet<products>();
        }
    
        public int id { get; set; }
        public string model { get; set; }
        public string category { get; set; }
        public string vendor { get; set; }
        public string manufacturer { get; set; }
    
        public virtual ICollection<products> products { get; set; }
        public virtual ICollection<products> products1 { get; set; }
        public virtual ICollection<products> products2 { get; set; }
        public virtual ICollection<products> products3 { get; set; }
    }
}
