//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeneciaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.stock = new HashSet<stock>();
            this.orderpurchase = new HashSet<orderpurchase>();
            this.ordersales = new HashSet<ordersales>();
            this.warehousepurchase = new HashSet<warehousepurchase>();
            this.warehousesales = new HashSet<warehousesales>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> unitprice { get; set; }
        public Nullable<int> model { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> vendor { get; set; }
        public Nullable<int> manufacturer { get; set; }
        public string notes { get; set; }
    
        public virtual productdetails productdetails { get; set; }
        public virtual productdetails productdetails1 { get; set; }
        public virtual productdetails productdetails2 { get; set; }
        public virtual productdetails productdetails3 { get; set; }
        public virtual ICollection<stock> stock { get; set; }
        public virtual ICollection<orderpurchase> orderpurchase { get; set; }
        public virtual ICollection<ordersales> ordersales { get; set; }
        public virtual ICollection<warehousepurchase> warehousepurchase { get; set; }
        public virtual ICollection<warehousesales> warehousesales { get; set; }
    }
}
