//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeneciaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualityofwater
    {
        public int id { get; set; }
        public Nullable<int> cage { get; set; }
        public string watercolor { get; set; }
        public Nullable<int> qualitydet { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
    
        public virtual cage cage1 { get; set; }
        public virtual qtype qtype { get; set; }
    }
}
