//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeneciaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_msg
    {
        public int code { get; set; }
        public Nullable<int> fromcode { get; set; }
        public Nullable<int> tocode { get; set; }
        public string toname { get; set; }
    }
}
