//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeneciaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehousepurchase
    {
        public int id { get; set; }
        public Nullable<int> prodid { get; set; }
        public string reason { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> totalprice { get; set; }
        public string notes { get; set; }
        public Nullable<int> emp { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual products products { get; set; }
    }
}
